### ISSUE TITLE
关于 S.T.D.R. 仿真器在 ubuntu16.04的安装。

### ISSUE THREAD

**Issue by yujincheng** [STAR-Center/fastGPOM#1]
作者好，这里是清华大学电子工程系线路与系统所高能效计算研究组。最近拜读了您的大作《Fast Gaussian Process Occupancy Maps》，很受启发，并且看到您在文章中提到您的工作已经开源。目前我们尝试学习您的工作，需要一些问题。
您提到您用的环境是 16.04 ，我安装16.04对应版本的ROS为Kinetic ，但是看到您用了 S.T.D.R. 的仿真器。目前只看到S.T.D.R.维护到indigo版本，没有 Kinetic 的版本。请问Kinetic 版本的 STDR 应该如何安装呢？
谢谢，盼复。

**Comment by KuangHaofei** [comment]
> 作者好，这里是清华大学电子工程系线路与系统所高能效计算研究组。最近拜读了您的大作《Fast Gaussian Process Occupancy Maps》，很受启发，并且看到您在文章中提到您的工作已经开源。目前我们尝试学习您的工作，需要一些问题。
> 您提到您用的环境是 16.04 ，我安装16.04对应版本的ROS为Kinetic ，但是看到您用了 S.T.D.R. 的仿真器。目前只看到S.T.D.R.维护到indigo版本，没有 Kinetic 的版本。请问Kinetic 版本的 STDR 应该如何安装呢？
> 谢谢，盼复。

**Comment by KuangHaofei** [comment]
> 作者好，这里是清华大学电子工程系线路与系统所高能效计算研究组。最近拜读了您的大作《Fast Gaussian Process Occupancy Maps》，很受启发，并且看到您在文章中提到您的工作已经开源。目前我们尝试学习您的工作，需要一些问题。
> 您提到您用的环境是 16.04 ，我安装16.04对应版本的ROS为Kinetic ，但是看到您用了 S.T.D.R. 的仿真器。目前只看到S.T.D.R.维护到indigo版本，没有 Kinetic 的版本。请问Kinetic 版本的 STDR 应该如何安装呢？
> 谢谢，盼复。

您好，感谢您支持我们的工作。

indigo版本的STDR可以在Kinetic版本下编译，您只需按照README里的指令下载编译后就能使用
```
cd your_catkin_workspace/src
git clone https://github.com/KuangHaofei/stdr_simulator.git
cd ..
catkin_make
source devel/setup.bash
roslaunch stdr_launchers server_with_map_and_gui_plus_robot.launch
```
Best ！

**Comment by yujincheng** [comment]
@KuangHaofei  虽然我们还是没能在16.04下编译成功S.T.D.R.，但是在ubuntu14.04 上部署了这个项目，也算是得到了解决，谢谢您。
