### ISSUE TITLE
关于 gpom_offline.py 和 gp_occ_map_offline.py 的区别

### ISSUE THREAD

**Issue by yujincheng** [STAR-Center/fastGPOM#2]
作者好，我又来了。在您的代码里，看到了两个项目
gpom_offline.py
和
gp_occ_map_offline.py
请问这两个工作有什么区别？

**Comment by Jarrome** [comment]
gp_occ_map_offline.py 是我们项目基于的别人的源码（见README）， gpom_offline.py是我们使用的源码。
